const icon = document.querySelector('.icon')
const city = document.querySelector('.city')
const temerature = document.querySelector('.temerature')
const weatherDescription = document.querySelector('.weather-description')
const windSpeed = document.querySelector('.wind_speed')
const precip = document.querySelector('.precip')
const pressure = document.querySelector('.pressure')
const humidity = document.querySelector('.humidity')
